import frappe
from erpnext.setup.utils import enable_all_roles_and_domains
from frappe.custom.doctype.custom_field.custom_field import create_custom_fields
from frappe.utils import now_datetime


def ensure_vunapos_custom_fields():
	create_custom_fields(
		{
			"POS Profile": [
				{
					"fieldname": "vunapos_tab",
					"label": "VunaPOS",
					"fieldtype": "Tab Break",
					"insert_after": "column_break_hwfg",
				},
				{
					"fieldname": "vunapos_sales_section",
					"label": "Sales Settings",
					"fieldtype": "Section Break",
					"insert_after": "vunapos_tab",
				},
				{
					"fieldname": "vunapos_item_prices_include_tax",
					"label": "Item Prices Include Tax",
					"fieldtype": "Check",
					"insert_after": "vunapos_sales_section",
					"description": (
						"Treat prices for items with an Item Tax Template as tax-inclusive in VunaPOS. "
						"Leave unchecked to add item taxes on top of the listed price."
					),
					"default": "0",
				},
				{
					"fieldname": "vunapos_allow_credit_sales",
					"label": "Allow Credit Sales",
					"fieldtype": "Check",
					"insert_after": "vunapos_item_prices_include_tax",
					"description": "Allow VunaPOS invoices to be submitted with an unpaid customer balance.",
					"default": "0",
				},
				{
					"fieldname": "vunapos_default_sale_type",
					"label": "Default Sale Type",
					"fieldtype": "Select",
					"options": "Cash Sale\nCredit Sale",
					"insert_after": "vunapos_allow_credit_sales",
					"description": "Choose whether VunaPOS checkout starts as a cash or credit sale.",
					"default": "Cash Sale",
					"depends_on": "eval:doc.vunapos_allow_credit_sales",
				},
				{
					"fieldname": "vunapos_allow_price_list_switching",
					"label": "Allow Price List Switching",
					"fieldtype": "Check",
					"insert_after": "vunapos_default_sale_type",
					"description": "Allow cashiers to select an approved selling price list for one VunaPOS sale.",
					"default": "0",
				},
				{
					"fieldname": "vunapos_allowed_price_lists",
					"label": "Allowed Price Lists",
					"fieldtype": "Table",
					"options": "VunaPOS Allowed Price List",
					"insert_after": "vunapos_allow_price_list_switching",
					"depends_on": "eval:doc.vunapos_allow_price_list_switching",
				},
				{
					"fieldname": "vunapos_queue_column_break",
					"fieldtype": "Column Break",
					"insert_after": "vunapos_allowed_price_lists",
				},
				{
					"fieldname": "vunapos_enable_background_submission",
					"label": "Enable Background Invoice Submission",
					"fieldtype": "Check",
					"insert_after": "vunapos_queue_column_break",
					"description": (
						"Accept validated VunaPOS sales after stock is reserved and submit their invoice "
						"in a background worker. Requires Enable Stock Reservation in Stock Settings; "
						"otherwise VunaPOS uses direct submission."
					),
					"default": "0",
				},
				{
					"fieldname": "vunapos_queue_max_attempts",
					"label": "Background Submission Attempts",
					"fieldtype": "Int",
					"insert_after": "vunapos_enable_background_submission",
					"description": "Maximum number of background submission attempts before review is required.",
					"default": "3",
					"depends_on": "eval:doc.vunapos_enable_background_submission",
				},
				{
					"fieldname": "vunapos_queue_processing_timeout_minutes",
					"label": "Background Processing Timeout (Minutes)",
					"fieldtype": "Int",
					"insert_after": "vunapos_queue_max_attempts",
					"description": "Time after which an abandoned processing attempt may be recovered.",
					"default": "5",
					"depends_on": "eval:doc.vunapos_enable_background_submission",
				},
			],
			"Sales Invoice Item": [
				{
					"fieldname": "vunapos_item_note",
					"label": "VunaPOS Item Note",
					"fieldtype": "Small Text",
					"insert_after": "description",
					"read_only": 1,
				},
				{
					"fieldname": "vunapos_pricing_override",
					"label": "VunaPOS Pricing Override",
					"fieldtype": "Data",
					"insert_after": "vunapos_item_note",
					"read_only": 1,
				},
				{
					"fieldname": "vunapos_pricing_override_by",
					"label": "VunaPOS Pricing Override By",
					"fieldtype": "Link",
					"options": "User",
					"insert_after": "vunapos_pricing_override",
					"read_only": 1,
				},
			],
			"POS Invoice Item": [
				{
					"fieldname": "vunapos_item_note",
					"label": "VunaPOS Item Note",
					"fieldtype": "Small Text",
					"insert_after": "description",
					"read_only": 1,
				},
				{
					"fieldname": "vunapos_pricing_override",
					"label": "VunaPOS Pricing Override",
					"fieldtype": "Data",
					"insert_after": "vunapos_item_note",
					"read_only": 1,
				},
				{
					"fieldname": "vunapos_pricing_override_by",
					"label": "VunaPOS Pricing Override By",
					"fieldtype": "Link",
					"options": "User",
					"insert_after": "vunapos_pricing_override",
					"read_only": 1,
				},
			],
			"Sales Invoice": [
				{
					"fieldname": "vunapos_invoice",
					"label": "VunaPOS Invoice",
					"fieldtype": "Check",
					"insert_after": "is_pos",
					"hidden": 1,
					"allow_on_submit": 1,
				},
				{
					"fieldname": "vunapos_held",
					"label": "VunaPOS Held",
					"fieldtype": "Check",
					"insert_after": "vunapos_invoice",
					"hidden": 1,
					"allow_on_submit": 1,
				},
				{
					"fieldname": "vunapos_credit_sale",
					"label": "VunaPOS Credit Sale",
					"fieldtype": "Check",
					"insert_after": "vunapos_held",
					"read_only": 1,
					"allow_on_submit": 1,
					"no_copy": 1,
				},
				{
					"fieldname": "vunapos_idempotency_key",
					"label": "VunaPOS Idempotency Key",
					"fieldtype": "Data",
					"insert_after": "vunapos_credit_sale",
					"hidden": 1,
					"allow_on_submit": 1,
					"no_copy": 1,
					"unique": 1,
					"search_index": 1,
				},
				{
					"fieldname": "vunapos_opening_entry",
					"label": "VunaPOS Opening Entry",
					"fieldtype": "Link",
					"options": "POS Opening Entry",
					"insert_after": "vunapos_idempotency_key",
					"read_only": 1,
					"allow_on_submit": 1,
					"no_copy": 1,
				},
				{
					"fieldname": "vunapos_session_cashier",
					"label": "VunaPOS Session Cashier",
					"fieldtype": "Link",
					"options": "User",
					"insert_after": "vunapos_opening_entry",
					"read_only": 1,
					"allow_on_submit": 1,
					"no_copy": 1,
				},
				{
					"fieldname": "vunapos_session_verified_at",
					"label": "VunaPOS Session Verified At",
					"fieldtype": "Datetime",
					"insert_after": "vunapos_session_cashier",
					"read_only": 1,
					"allow_on_submit": 1,
					"no_copy": 1,
				},
				{
					"fieldname": "vunapos_closing_entry",
					"label": "VunaPOS Closing Entry",
					"fieldtype": "Link",
					"options": "POS Closing Entry",
					"insert_after": "vunapos_session_verified_at",
					"read_only": 1,
					"allow_on_submit": 1,
					"no_copy": 1,
				},
				{
					"fieldname": "vunapos_queue_status",
					"label": "VunaPOS Queue Status",
					"fieldtype": "Select",
					"options": "\nQueued\nProcessing\nSubmitted\nFailed\nRequires Review\nCancelled",
					"insert_after": "vunapos_closing_entry",
					"read_only": 1,
					"allow_on_submit": 1,
					"no_copy": 1,
					"search_index": 1,
				},
				{
					"fieldname": "vunapos_queue_attempts",
					"label": "VunaPOS Queue Attempts",
					"fieldtype": "Int",
					"insert_after": "vunapos_queue_status",
					"read_only": 1,
					"allow_on_submit": 1,
					"no_copy": 1,
					"default": "0",
				},
				{
					"fieldname": "vunapos_queue_error",
					"label": "VunaPOS Queue Error",
					"fieldtype": "Small Text",
					"insert_after": "vunapos_queue_attempts",
					"read_only": 1,
					"allow_on_submit": 1,
					"no_copy": 1,
				},
				{
					"fieldname": "vunapos_queue_created_at",
					"label": "VunaPOS Queued At",
					"fieldtype": "Datetime",
					"insert_after": "vunapos_queue_error",
					"read_only": 1,
					"allow_on_submit": 1,
					"no_copy": 1,
				},
				{
					"fieldname": "vunapos_queue_started_at",
					"label": "VunaPOS Processing Started At",
					"fieldtype": "Datetime",
					"insert_after": "vunapos_queue_created_at",
					"read_only": 1,
					"allow_on_submit": 1,
					"no_copy": 1,
				},
				{
					"fieldname": "vunapos_queue_completed_at",
					"label": "VunaPOS Queue Completed At",
					"fieldtype": "Datetime",
					"insert_after": "vunapos_queue_started_at",
					"read_only": 1,
					"allow_on_submit": 1,
					"no_copy": 1,
				},
				{
					"fieldname": "vunapos_queue_job_id",
					"label": "VunaPOS Queue Job ID",
					"fieldtype": "Data",
					"insert_after": "vunapos_queue_completed_at",
					"read_only": 1,
					"allow_on_submit": 1,
					"no_copy": 1,
				},
				{
					"fieldname": "vunapos_reservation_fingerprint",
					"label": "VunaPOS Reservation Fingerprint",
					"fieldtype": "Data",
					"insert_after": "vunapos_queue_job_id",
					"hidden": 1,
					"read_only": 1,
					"allow_on_submit": 1,
					"no_copy": 1,
				},
			],
			"POS Invoice": [
				{
					"fieldname": "vunapos_invoice",
					"label": "VunaPOS Invoice",
					"fieldtype": "Check",
					"insert_after": "pos_profile",
					"hidden": 1,
					"allow_on_submit": 1,
				},
				{
					"fieldname": "vunapos_held",
					"label": "VunaPOS Held",
					"fieldtype": "Check",
					"insert_after": "vunapos_invoice",
					"hidden": 1,
					"allow_on_submit": 1,
				},
				{
					"fieldname": "vunapos_credit_sale",
					"label": "VunaPOS Credit Sale",
					"fieldtype": "Check",
					"insert_after": "vunapos_held",
					"read_only": 1,
					"allow_on_submit": 1,
					"no_copy": 1,
				},
				{
					"fieldname": "vunapos_idempotency_key",
					"label": "VunaPOS Idempotency Key",
					"fieldtype": "Data",
					"insert_after": "vunapos_credit_sale",
					"hidden": 1,
					"allow_on_submit": 1,
					"no_copy": 1,
					"unique": 1,
					"search_index": 1,
				},
				{
					"fieldname": "vunapos_opening_entry",
					"label": "VunaPOS Opening Entry",
					"fieldtype": "Link",
					"options": "POS Opening Entry",
					"insert_after": "vunapos_idempotency_key",
					"read_only": 1,
					"allow_on_submit": 1,
					"no_copy": 1,
				},
				{
					"fieldname": "vunapos_session_cashier",
					"label": "VunaPOS Session Cashier",
					"fieldtype": "Link",
					"options": "User",
					"insert_after": "vunapos_opening_entry",
					"read_only": 1,
					"allow_on_submit": 1,
					"no_copy": 1,
				},
				{
					"fieldname": "vunapos_session_verified_at",
					"label": "VunaPOS Session Verified At",
					"fieldtype": "Datetime",
					"insert_after": "vunapos_session_cashier",
					"read_only": 1,
					"allow_on_submit": 1,
					"no_copy": 1,
				},
				{
					"fieldname": "vunapos_closing_entry",
					"label": "VunaPOS Closing Entry",
					"fieldtype": "Link",
					"options": "POS Closing Entry",
					"insert_after": "vunapos_session_verified_at",
					"read_only": 1,
					"allow_on_submit": 1,
					"no_copy": 1,
				},
				{
					"fieldname": "vunapos_queue_status",
					"label": "VunaPOS Queue Status",
					"fieldtype": "Select",
					"options": "\nQueued\nProcessing\nSubmitted\nFailed\nRequires Review\nCancelled",
					"insert_after": "vunapos_closing_entry",
					"read_only": 1,
					"allow_on_submit": 1,
					"no_copy": 1,
					"search_index": 1,
				},
				{
					"fieldname": "vunapos_queue_attempts",
					"label": "VunaPOS Queue Attempts",
					"fieldtype": "Int",
					"insert_after": "vunapos_queue_status",
					"read_only": 1,
					"allow_on_submit": 1,
					"no_copy": 1,
					"default": "0",
				},
				{
					"fieldname": "vunapos_queue_error",
					"label": "VunaPOS Queue Error",
					"fieldtype": "Small Text",
					"insert_after": "vunapos_queue_attempts",
					"read_only": 1,
					"allow_on_submit": 1,
					"no_copy": 1,
				},
				{
					"fieldname": "vunapos_queue_created_at",
					"label": "VunaPOS Queued At",
					"fieldtype": "Datetime",
					"insert_after": "vunapos_queue_error",
					"read_only": 1,
					"allow_on_submit": 1,
					"no_copy": 1,
				},
				{
					"fieldname": "vunapos_queue_started_at",
					"label": "VunaPOS Processing Started At",
					"fieldtype": "Datetime",
					"insert_after": "vunapos_queue_created_at",
					"read_only": 1,
					"allow_on_submit": 1,
					"no_copy": 1,
				},
				{
					"fieldname": "vunapos_queue_completed_at",
					"label": "VunaPOS Queue Completed At",
					"fieldtype": "Datetime",
					"insert_after": "vunapos_queue_started_at",
					"read_only": 1,
					"allow_on_submit": 1,
					"no_copy": 1,
				},
				{
					"fieldname": "vunapos_queue_job_id",
					"label": "VunaPOS Queue Job ID",
					"fieldtype": "Data",
					"insert_after": "vunapos_queue_completed_at",
					"read_only": 1,
					"allow_on_submit": 1,
					"no_copy": 1,
				},
				{
					"fieldname": "vunapos_reservation_fingerprint",
					"label": "VunaPOS Reservation Fingerprint",
					"fieldtype": "Data",
					"insert_after": "vunapos_queue_job_id",
					"hidden": 1,
					"read_only": 1,
					"allow_on_submit": 1,
					"no_copy": 1,
				},
			],
			"Payment Entry": [
				{
					"fieldname": "vunapos_payment",
					"label": "VunaPOS Payment",
					"fieldtype": "Check",
					"insert_after": "mode_of_payment",
					"hidden": 1,
					"allow_on_submit": 1,
				},
				{
					"fieldname": "vunapos_idempotency_key",
					"label": "VunaPOS Idempotency Key",
					"fieldtype": "Data",
					"insert_after": "vunapos_payment",
					"hidden": 1,
					"unique": 1,
					"no_copy": 1,
					"allow_on_submit": 1,
				},
				{
					"fieldname": "vunapos_opening_entry",
					"label": "VunaPOS Opening Entry",
					"fieldtype": "Link",
					"options": "POS Opening Entry",
					"insert_after": "vunapos_idempotency_key",
					"read_only": 1,
					"no_copy": 1,
					"allow_on_submit": 1,
				},
				{
					"fieldname": "vunapos_session_cashier",
					"label": "VunaPOS Session Cashier",
					"fieldtype": "Link",
					"options": "User",
					"insert_after": "vunapos_opening_entry",
					"read_only": 1,
					"no_copy": 1,
					"allow_on_submit": 1,
				},
				{
					"fieldname": "vunapos_closing_entry",
					"label": "VunaPOS Closing Entry",
					"fieldtype": "Link",
					"options": "POS Closing Entry",
					"insert_after": "vunapos_session_cashier",
					"read_only": 1,
					"no_copy": 1,
					"allow_on_submit": 1,
				},
				{
					"fieldname": "vunapos_receipt_type",
					"label": "VunaPOS Receipt Type",
					"fieldtype": "Select",
					"options": "Outstanding Invoice Payment\nCustomer Advance",
					"insert_after": "vunapos_closing_entry",
					"read_only": 1,
					"allow_on_submit": 1,
				},
				{
					"fieldname": "vunapos_reconciled_opening_entry",
					"label": "VunaPOS Reconciled Opening Entry",
					"fieldtype": "Link",
					"options": "POS Opening Entry",
					"insert_after": "vunapos_receipt_type",
					"read_only": 1,
					"allow_on_submit": 1,
				},
				{
					"fieldname": "vunapos_reconciled_amount",
					"label": "VunaPOS Reconciled Amount",
					"fieldtype": "Currency",
					"insert_after": "vunapos_reconciled_opening_entry",
					"read_only": 1,
					"allow_on_submit": 1,
				},
			],
		},
		ignore_validate=True,
	)
	ensure_sales_invoice_stock_reservation_option()


def ensure_sales_invoice_stock_reservation_option():
	legacy_setter = frappe.db.get_value(
		"Property Setter",
		{
			"name": "Stock Reservation Entry-main-options",
			"doc_type": "Stock Reservation Entry",
			"field_name": ["is", "not set"],
			"property": "options",
			"module": "VunaPOS",
		},
		"name",
	)
	if legacy_setter:
		frappe.delete_doc("Property Setter", legacy_setter, ignore_permissions=True)
		frappe.clear_cache(doctype="Stock Reservation Entry")

	field = frappe.get_meta("Stock Reservation Entry").get_field("voucher_type")
	options = [option.strip() for option in (field.options or "").splitlines() if option.strip()]
	if "Sales Invoice" in options:
		return

	options.append("Sales Invoice")
	frappe.make_property_setter(
		{
			"doctype": "Stock Reservation Entry",
			"doctype_or_field": "DocField",
			"fieldname": "voucher_type",
			"property": "options",
			"property_type": "Text",
			"value": "\n" + "\n".join(options),
		},
		ignore_validate=True,
		is_system_generated=False,
		module="VunaPOS",
	)
	frappe.clear_cache(doctype="Stock Reservation Entry")


def before_tests():
	frappe.clear_cache()
	# complete setup if missing
	from frappe.desk.page.setup_wizard.setup_wizard import setup_complete

	year = now_datetime().year
	if not frappe.get_list("Company"):
		setup_complete(
			{
				"currency": "KES",
				"full_name": "Test User",
				"company_name": "Vuna Technologies Limited",
				"timezone": "Africa/Nairobi",
				"company_abbr": "NL",
				"industry": "Software",
				"country": "Kenya",
				"fy_start_date": f"{year}-01-01",
				"fy_end_date": f"{year}-12-31",
				"language": "english",
				"company_tagline": "Testing",
				"email": "test@vuna.co.ke",
				"password": "test",
				"chart_of_accounts": "Standard",
			}
		)

	enable_all_roles_and_domains()
	ensure_vunapos_custom_fields()
	# Manually commit to save setup progress in case of timeout
	frappe.db.commit()  # nosemgrep
