import { useFrappeGetCall, useFrappePostCall } from "frappe-react-sdk";
import type { ReactNode } from "react";
import { ArrowLeft, CreditCard, Printer, ShoppingCart, UserRound } from "lucide-react";

import { Button } from "../../../components/ui/Button";
import { navigateToCustomer, navigateToCustomerPayment, navigateToPosPage } from "../../../lib/stores/navigationStore";
import { unwrapVunaResponse, vunaMethods } from "../../../services/vunaApi";
import type { CustomerDTO, InvoiceDTO } from "../types";

type Details = InvoiceDTO & { currency?: string; posting_time?: string; due_date?: string; status: string; is_return: boolean; return_against?: string; pos_profile?: string; warehouse?: string; opening_entry?: string; cashier?: string; closing_entry?: string; local_ref?: string; returns: Array<{ name: string; posting_date: string; grand_total: number; docstatus: number }>; payment_entries: Array<{ name: string; posting_date: string; mode_of_payment?: string; received_amount: number; allocated_amount: number; unallocated_amount: number; docstatus: number }> };
type Props = { invoice: string; posProfile?: string; onStartSale: (customer: CustomerDTO) => void };

export function InvoiceDetailsPage({ invoice, posProfile, onStartSale }: Props) {
	const call = useFrappeGetCall<unknown>(vunaMethods.getInvoiceDetails, { pos_profile: posProfile, invoice_name: invoice }, posProfile ? ["vunapos_invoice_details", posProfile, invoice] : null);
	const printCall = useFrappePostCall(vunaMethods.renderInvoice);
	let details: Details | null = null; let parseError = "";
	try { if (call.data) details = unwrapVunaResponse<Details>(call.data); } catch (error) { parseError = error instanceof Error ? error.message : "Unable to load invoice"; }
	async function printReceipt() {
		if (!details) return;
		try {
			const response = await printCall.call({ invoice_doctype: details.doctype, invoice_name: details.name });
			const payload = unwrapVunaResponse<{ html: string }>(response); const frame = window.open("", "_blank");
			if (!frame) throw new Error("Allow pop-ups to print the receipt.");
			frame.opener = null; frame.document.write(payload.html); frame.document.close(); frame.focus(); frame.print();
		} catch (error) { window.alert(error instanceof Error ? error.message : "Unable to print receipt"); }
	}
	if (call.isLoading) return <section className="flex flex-1 items-center justify-center"><p className="text-sm text-on-surface-variant">Loading invoice...</p></section>;
	if (!details || parseError || call.error) return <section className="flex flex-1 items-center justify-center p-6"><div className="text-center"><p className="text-sm text-error">{parseError || call.error?.message || "Invoice not found"}</p><Button className="mt-3" variant="ghost" onClick={() => navigateToPosPage("Invoices")}>Back to invoices</Button></div></section>;
	const total = details.totals.rounded_total || details.totals.grand_total || 0;
	return <section className="min-h-0 flex-1 overflow-y-auto border-t border-outline-variant bg-surface p-4 pb-[84px] lg:pb-4"><div className="mx-auto flex max-w-6xl flex-col gap-4">
		<div className="flex flex-wrap items-start justify-between gap-3"><div className="flex gap-3"><button className="mt-1" onClick={() => navigateToPosPage("Invoices")} aria-label="Back"><ArrowLeft className="size-5"/></button><div><h2 className="text-xl font-semibold">{details.name}</h2><p className="text-sm text-on-surface-variant">{details.posting_date} {details.posting_time || ""} · {details.status}</p></div></div><div className="flex flex-wrap gap-2"><Button variant="ghost" onClick={printReceipt}><Printer className="mr-2 size-4"/>Print receipt</Button><a href={`/app/${details.doctype.toLowerCase().replaceAll(" ", "-")}/${encodeURIComponent(details.name)}`} target="_blank" rel="noreferrer"><Button variant="ghost">Open in ERPNext</Button></a></div></div>
		<div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Summary label="Grand total" value={money(total, details.currency)}/><Summary label="Paid" value={money(details.totals.paid_amount || 0, details.currency)}/><Summary label="Outstanding" value={money(details.totals.outstanding_amount || 0, details.currency)}/><Summary label="Items" value={String(details.items.reduce((sum, row) => sum + Number(row.qty), 0))}/></div>
		<div className="grid gap-4 lg:grid-cols-2"><Card title="Customer"><p className="font-medium">{details.customer_name || details.customer}</p><p className="text-sm text-on-surface-variant">{details.customer}</p><div className="mt-3 flex gap-2"><Button size="sm" variant="ghost" onClick={() => navigateToCustomer(details.customer || "")}><UserRound className="mr-1 size-4"/>Customer</Button><Button size="sm" variant="ghost" disabled={!Number(details.totals.outstanding_amount)} onClick={() => navigateToCustomerPayment(details.customer || "", details.name)}><CreditCard className="mr-1 size-4"/>Receive payment</Button><Button size="sm" onClick={() => onStartSale({ customer: details.customer || "", customer_name: details.customer_name || details.customer || "" })}><ShoppingCart className="mr-1 size-4"/>New sale</Button></div></Card><Card title="POS audit"><KeyValue label="Cashier" value={details.cashier}/><KeyValue label="POS Profile" value={details.pos_profile}/><KeyValue label="Opening Entry" value={details.opening_entry}/><KeyValue label="Closing Entry" value={details.closing_entry}/><KeyValue label="Warehouse" value={details.warehouse}/><KeyValue label="Local reference" value={details.local_ref}/></Card></div>
		<Card title="Items"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="text-xs text-on-surface-variant"><tr><th className="py-2">Item</th><th>Qty</th><th>Rate</th><th>Amount</th><th>Batch</th></tr></thead><tbody>{details.items.map((row) => <tr key={row.row_name} className="border-t border-outline-variant"><td className="py-3"><p className="font-medium">{row.item_name}</p><p className="text-xs text-on-surface-variant">{row.item_code}</p></td><td>{row.qty} {row.uom || ""}</td><td>{money(row.rate, details.currency)}</td><td>{money(row.amount, details.currency)}</td><td>{row.batch_allocations?.map((batch) => `${batch.batch_no} (${batch.qty})`).join(", ") || row.batch_no || "-"}</td></tr>)}</tbody></table></div></Card>
		<div className="grid gap-4 lg:grid-cols-2"><Card title="Checkout payments">{details.payments?.length ? details.payments.map((row) => <KeyValue key={row.mode_of_payment} label={row.mode_of_payment} value={money(row.amount, details.currency)}/>) : <p className="text-sm text-on-surface-variant">No checkout payment rows.</p>}</Card><Card title="Taxes and totals">{details.taxes?.map((row, index) => <KeyValue key={`${row.account_head}-${index}`} label={row.description || row.account_head || "Tax"} value={money(row.tax_amount || 0, details.currency)}/>) }<KeyValue label="Net total" value={money(details.totals.net_total || 0, details.currency)}/><KeyValue label="Grand total" value={money(total, details.currency)}/></Card></div>
		<div className="grid gap-4 lg:grid-cols-2"><Card title="Linked Payment Entries">{details.payment_entries.length ? details.payment_entries.map((row) => <div key={row.name} className="border-t border-outline-variant py-2 first:border-0"><a className="font-medium text-primary" href={`/app/payment-entry/${encodeURIComponent(row.name)}`} target="_blank" rel="noreferrer">{row.name}</a><p className="text-xs text-on-surface-variant">{row.posting_date} · {row.mode_of_payment || "Unspecified"} · Allocated {money(row.allocated_amount, details.currency)}</p></div>) : <p className="text-sm text-on-surface-variant">No linked Payment Entries.</p>}</Card><Card title="Returns and credit notes">{details.returns.length ? details.returns.map((row) => <div key={row.name} className="border-t border-outline-variant py-2 first:border-0"><a className="font-medium text-primary" href={`/app/${details.doctype.toLowerCase().replaceAll(" ", "-")}/${encodeURIComponent(row.name)}`} target="_blank" rel="noreferrer">{row.name}</a><p className="text-xs text-on-surface-variant">{row.posting_date} · {money(row.grand_total, details.currency)} · {row.docstatus === 2 ? "Cancelled" : "Submitted"}</p></div>) : <p className="text-sm text-on-surface-variant">No returns have been created.</p>}</Card></div>
	</div></section>;
}

function Card({ title, children }: { title: string; children: ReactNode }) { return <div className="rounded-lg border border-outline-variant p-4"><h3 className="mb-3 font-semibold">{title}</h3>{children}</div>; }
function Summary({ label, value }: { label: string; value: string }) { return <div className="rounded-lg border border-outline-variant bg-surface-container-low p-4"><p className="text-xs text-on-surface-variant">{label}</p><p className="mt-1 text-lg font-semibold">{value}</p></div>; }
function KeyValue({ label, value }: { label: string; value?: string | number | null }) { return <div className="flex justify-between gap-3 border-t border-outline-variant py-2 text-sm first:border-0"><span className="text-on-surface-variant">{label}</span><span className="text-right font-medium">{value || "-"}</span></div>; }
function money(value: number, currency?: string) { return new Intl.NumberFormat(undefined, { style: currency ? "currency" : "decimal", currency: currency || undefined }).format(value); }
