import { useState, type ReactNode } from "react";
import { useFrappeGetCall } from "frappe-react-sdk";

import { Button } from "../../../components/ui/Button";
import { unwrapVunaResponse, vunaMethods } from "../../../services/vunaApi";
import type { HeldInvoiceDTO, ModeOfPaymentDTO } from "../types";
import { HeldInvoicesPanel } from "./HeldInvoicesPanel";
import { QueueInspectorPanel } from "./QueueInspectorPanel";

type Props = { posProfile?: string; currency?: string; paymentModes: ModeOfPaymentDTO[]; heldInvoices?: HeldInvoiceDTO[]; heldLoading: boolean; onBack: () => void; onRefreshHeld: () => void; onRestoreHeld: (invoice: HeldInvoiceDTO) => void };
type Filters = { invoice: string; customer: string; from_date: string; to_date: string; status: string; payment_mode: string; current_shift: string };
type HistoryInvoice = { name: string; doctype: string; posting_date: string; posting_time?: string; customer: string; customer_name?: string; currency?: string; grand_total: number; paid_amount: number; outstanding_amount: number; total_qty: number; status: string; is_return: boolean; return_against?: string; vunapos_session_cashier?: string; vunapos_opening_entry?: string; vunapos_closing_entry?: string; local_ref?: string; payments: Array<{ mode_of_payment: string; amount: number }> };
type History = { invoices: HistoryInvoice[]; has_more: boolean; opening_entry?: string; summary: { invoice_count: number; returns_count: number; gross_sales: number; returns: number; net_sales: number; outstanding: number } };
const fieldClass = "rounded-md border border-outline-variant bg-surface px-3 py-2 text-sm outline-none focus:border-primary";

export function InvoicesPage({ posProfile, currency, paymentModes, heldInvoices, heldLoading, onBack, onRefreshHeld, onRestoreHeld }: Props) {
	const [tab, setTab] = useState<"history" | "issues">("history");
	const [filters, setFilters] = useState<Filters>({ invoice: "", customer: "", from_date: "", to_date: "", status: "", payment_mode: "", current_shift: "1" });
	const [start, setStart] = useState(0);
	const call = useFrappeGetCall<unknown>(vunaMethods.getInvoiceHistory, { pos_profile: posProfile, ...filters, start, page_length: 50 }, posProfile && tab === "history" ? ["vunapos_invoice_history", posProfile, filters, start] : null);
	let history: History | null = null; let error = call.error?.message || "";
	try { if (call.data) history = unwrapVunaResponse<History>(call.data); } catch (err) { error = err instanceof Error ? err.message : "Unable to load invoice history"; }
	const update = (field: keyof Filters, value: string) => { setFilters((current) => ({ ...current, [field]: value })); setStart(0); };

	return <section className="min-h-0 flex-1 overflow-y-auto border-t border-outline-variant bg-surface p-4 pb-[84px] lg:pb-4"><div className="mx-auto flex w-full max-w-6xl flex-col gap-4">
		<div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-semibold">Invoices</h2><p className="text-sm text-on-surface-variant">Review completed sales and resolve held or failed transactions.</p></div><Button variant="ghost" onClick={onBack}>Back to POS</Button></div>
		<div className="flex border-b border-outline-variant"><Tab active={tab === "history"} onClick={() => setTab("history")}>Sales History</Tab><Tab active={tab === "issues"} onClick={() => setTab("issues")}>Held &amp; Sync Issues</Tab></div>
		{tab === "issues" ? <><HeldInvoicesPanel currency={currency} heldInvoices={heldInvoices} isLoading={heldLoading} onRefresh={onRefreshHeld} onRestore={onRestoreHeld}/><QueueInspectorPanel/></> : <>
			<div className="grid gap-3 rounded-lg border border-outline-variant p-4 sm:grid-cols-2 lg:grid-cols-4"><input className={fieldClass} placeholder="Invoice number" value={filters.invoice} onChange={(event) => update("invoice", event.target.value)}/><input className={fieldClass} placeholder="Customer ID" value={filters.customer} onChange={(event) => update("customer", event.target.value)}/><input className={fieldClass} type="date" aria-label="From date" value={filters.from_date} onChange={(event) => update("from_date", event.target.value)}/><input className={fieldClass} type="date" aria-label="To date" value={filters.to_date} onChange={(event) => update("to_date", event.target.value)}/><select className={fieldClass} value={filters.status} onChange={(event) => update("status", event.target.value)}><option value="">All statuses</option>{["Paid", "Partly Paid", "Unpaid", "Overdue", "Credit Note", "Cancelled"].map((value) => <option key={value}>{value}</option>)}</select><select className={fieldClass} value={filters.payment_mode} onChange={(event) => update("payment_mode", event.target.value)}><option value="">All payment modes</option>{paymentModes.map((row) => <option key={row.mode_of_payment}>{row.mode_of_payment}</option>)}</select><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={filters.current_shift === "1"} onChange={(event) => update("current_shift", event.target.checked ? "1" : "0")}/>Current shift only</label><Button variant="ghost" onClick={() => { setFilters({ invoice: "", customer: "", from_date: "", to_date: "", status: "", payment_mode: "", current_shift: "1" }); setStart(0); }}>Clear filters</Button></div>
			{error ? <Notice>{error}</Notice> : null}
			{history ? <><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Summary label="Invoices" value={String(history.summary.invoice_count)}/><Summary label="Gross sales" value={money(history.summary.gross_sales, currency)}/><Summary label="Returns" value={money(history.summary.returns, currency)}/><Summary label="Outstanding" value={money(history.summary.outstanding, currency)}/></div><div className="overflow-x-auto rounded-lg border border-outline-variant"><table className="w-full min-w-[1050px] text-left text-sm"><thead className="bg-surface-container-low text-xs text-on-surface-variant"><tr><th className="px-3 py-3">Invoice</th><th>Date / time</th><th>Customer</th><th>Cashier / shift</th><th>Items</th><th>Payment</th><th>Total</th><th>Outstanding</th><th>Status</th></tr></thead><tbody>{history.invoices.length ? history.invoices.map((row) => <tr key={row.name} className="border-t border-outline-variant"><td className="px-3 py-3"><a className="font-medium text-primary hover:underline" href={`/app/${row.doctype.toLowerCase().replaceAll(" ", "-")}/${encodeURIComponent(row.name)}`} target="_blank" rel="noreferrer">{row.name}</a>{row.local_ref ? <span className="block text-xs text-on-surface-variant">{row.local_ref}</span> : null}</td><td>{row.posting_date}<span className="block text-xs text-on-surface-variant">{row.posting_time || ""}</span></td><td>{row.customer_name || row.customer}<span className="block text-xs text-on-surface-variant">{row.customer}</span></td><td>{row.vunapos_session_cashier || "-"}<span className="block text-xs text-on-surface-variant">{row.vunapos_opening_entry || "No shift"}</span></td><td>{row.total_qty}</td><td>{row.payments.length ? row.payments.map((payment) => <span className="block" key={payment.mode_of_payment}>{payment.mode_of_payment}: {money(payment.amount, row.currency || currency)}</span>) : "-"}</td><td className="font-medium">{money(row.grand_total, row.currency || currency)}</td><td>{money(row.outstanding_amount, row.currency || currency)}</td><td><Status value={row.status}/></td></tr>) : <tr><td colSpan={9} className="p-8 text-center text-on-surface-variant">No invoices match these filters.</td></tr>}</tbody></table></div><div className="flex justify-end gap-2"><Button variant="ghost" disabled={!start} onClick={() => setStart(Math.max(0, start - 50))}>Previous</Button><Button variant="ghost" disabled={!history.has_more} onClick={() => setStart(start + 50)}>Next</Button></div></> : call.isLoading ? <p className="py-12 text-center text-sm text-on-surface-variant">Loading invoice history...</p> : null}
		</>}
	</div></section>;
}

function Tab({ active, onClick, children }: { active: boolean; onClick: () => void; children: ReactNode }) { return <button className={`px-5 py-3 text-sm font-medium ${active ? "border-b-2 border-primary text-primary" : "text-on-surface-variant"}`} onClick={onClick}>{children}</button>; }
function Summary({ label, value }: { label: string; value: string }) { return <div className="rounded-lg border border-outline-variant bg-surface-container-low p-4"><p className="text-xs text-on-surface-variant">{label}</p><p className="mt-1 text-lg font-semibold">{value}</p></div>; }
function Status({ value }: { value: string }) { return <span className={`rounded-full px-2 py-1 text-xs font-medium ${value === "Paid" ? "bg-secondary-container text-on-secondary-container" : value === "Cancelled" || value === "Overdue" ? "bg-error-container text-on-error-container" : "bg-surface-container-high text-on-surface"}`}>{value}</span>; }
function Notice({ children }: { children: ReactNode }) { return <div className="rounded-md border border-error bg-error-container p-3 text-sm text-on-error-container">{children}</div>; }
function money(value: number, currency?: string) { return new Intl.NumberFormat(undefined, { style: currency ? "currency" : "decimal", currency: currency || undefined }).format(value); }
